# Generated by Django 5.1.7 on 2025-03-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
