# Generated by Django 5.1.7 on 2025-03-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="uniqueseatbooking",
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name="uniqueseatbooking",
            table="unique_seat_booking",
        ),
    ]
