# Generated by Django 5.1.7 on 2025-03-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_customer_uuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="uuser",
            new_name="user",
        ),
    ]
