# Generated by Django 5.1.7 on 2025-03-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_uniqueseatbooking_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uniqueseatbooking",
            old_name="showtime",
            new_name="show",
        ),
    ]
