# Generated by Django 5.1.7 on 2025-03-17 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_rename_showtime_uniqueseatbooking_show"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uniqueseatbooking",
            name="show",
            field=models.ForeignKey(
                db_column="show_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.showtime",
            ),
        ),
    ]
