# Generated by Django 5.1.7 on 2025-03-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_rename_uuser_customer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="seat_number",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="seat",
            name="status",
            field=models.CharField(
                choices=[("available", "Available"), ("booked", "Booked")],
                default="available",
                max_length=20,
            ),
        ),
    ]
