# Generated by Django 5.1.7 on 2025-03-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_alter_uniqueseatbooking_show"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uniqueseatbooking",
            name="city",
        ),
        migrations.RemoveField(
            model_name="uniqueseatbooking",
            name="event",
        ),
        migrations.RemoveField(
            model_name="uniqueseatbooking",
            name="screen",
        ),
        migrations.RemoveField(
            model_name="uniqueseatbooking",
            name="seat",
        ),
        migrations.RemoveField(
            model_name="uniqueseatbooking",
            name="show",
        ),
        migrations.RemoveField(
            model_name="uniqueseatbooking",
            name="tier",
        ),
        migrations.AddField(
            model_name="uniqueseatbooking",
            name="city_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="uniqueseatbooking",
            name="event_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="uniqueseatbooking",
            name="screen_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="uniqueseatbooking",
            name="seat_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="uniqueseatbooking",
            name="show_id",
            field=models.IntegerField(db_column="show_id", default=1),
        ),
        migrations.AddField(
            model_name="uniqueseatbooking",
            name="tier_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="uniqueseatbooking",
            name="date",
            field=models.CharField(default="2025-03-17", max_length=20),
        ),
    ]
