# Generated by Django 5.1.7 on 2025-03-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_alter_seat_seat_number_alter_seat_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="bookings.tier",
            ),
        ),
    ]
