# Generated by Django 5.1.7 on 2025-03-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_remove_uniqueseatbooking_city_and_more"),
    ]

    operations = []
